import type { Actividad, Consejo, DocumentoComedor, Noticia } from "@/types/domain";

export const mockNoticias: Noticia[] = [
  {
    id: 1,
    slug: "fiesta-fin-curso",
    titulo_es: "Fiesta de fin de curso",
    titulo_eu: "Ikasturte amaierako jaia",
    resumen_es: "Programa y horarios para la fiesta de final de curso.",
    resumen_eu: "Ikasturte amaierako jaiaren egitaraua eta ordutegiak.",
    contenido_es: "Publicaremos en esta seccion toda la informacion oficial y documentos asociados.",
    contenido_eu: "Atal honetan informazio ofizial guztia eta lotutako dokumentuak argitaratuko ditugu.",
    imagen_url: "https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?auto=format&fit=crop&w=1200&q=80",
    fecha_publicacion: "2026-05-01",
    publicada: true,
  },
  {
    id: 2,
    slug: "asamblea-general",
    titulo_es: "Asamblea general ordinaria",
    titulo_eu: "Ohiko batzar nagusia",
    resumen_es: "Convocatoria, orden del dia y documentacion previa.",
    resumen_eu: "Deialdia, gai-zerrenda eta aurreko dokumentazioa.",
    contenido_es: "Aqui apareceran las actas y acuerdos de forma accesible para las familias.",
    contenido_eu: "Hemen agiriak eta akordioak familientzat eskuragarri argitaratuko dira.",
    imagen_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80",
    fecha_publicacion: "2026-04-20",
    publicada: true,
  },
];

export const mockActividades: Actividad[] = [
  {
    id: 1,
    slug: "taller-lectura",
    titulo_es: "Taller de lectura en familia",
    titulo_eu: "Familia irakurketa tailerra",
    descripcion_es: "Dinamicas para mejorar habitos lectores en casa.",
    descripcion_eu: "Etxeko irakurketa ohiturak hobetzeko dinamikak.",
    fecha_inicio: "2026-05-20",
    fecha_fin: "2026-05-20",
    ubicacion: "Biblioteca del centro",
    tipo: "Taller",
    publicada: true,
  },
  {
    id: 2,
    slug: "mercadillo-solidario",
    titulo_es: "Mercadillo solidario",
    titulo_eu: "Azoka solidarioa",
    descripcion_es: "Recaudacion para proyectos de mejora escolar.",
    descripcion_eu: "Eskola hobetzeko proiektuetarako diru-bilketa.",
    fecha_inicio: "2026-06-02",
    fecha_fin: "2026-06-02",
    ubicacion: "Patio principal",
    tipo: "Comunidad",
    publicada: true,
  },
  {
    id: 3,
    slug: "reunion-junta-mayo",
    titulo_es: "Reunion de la Junta Directiva",
    titulo_eu: "Batzorde nagusiaren bilera",
    descripcion_es: "Reunion ordinaria mensual de la junta directiva de la AFA.",
    descripcion_eu: "AFAren batzorde nagusiaren hilero bilerargia.",
    fecha_inicio: "2026-05-13",
    fecha_fin: "2026-05-13",
    ubicacion: "Sala de reuniones del colegio",
    tipo: "Reunion",
    publicada: true,
  },
  {
    id: 4,
    slug: "excursion-bardenas",
    titulo_es: "Excursion a las Bardenas Reales",
    titulo_eu: "Bardeetako irteera",
    descripcion_es: "Excursion familiar a las Bardenas Reales. Inscripcion previa obligatoria.",
    descripcion_eu: "Familia-irteera Bardeetara. Aurretiazko izena ematea nahitaezkoa da.",
    fecha_inicio: "2026-05-23",
    fecha_fin: "2026-05-23",
    ubicacion: "Bardenas Reales, Navarra",
    tipo: "Excursion",
    publicada: true,
  },
  {
    id: 5,
    slug: "taller-robotica",
    titulo_es: "Taller de robotica para familias",
    titulo_eu: "Familientzako robotika tailerra",
    descripcion_es: "Introduccion a la programacion y robotica con materiales del aula de extraescolares.",
    descripcion_eu: "Eskolaz kanpoko gelako materialekin programazio eta robotikaren sarrera.",
    fecha_inicio: "2026-05-28",
    fecha_fin: "2026-05-28",
    ubicacion: "Aula de informatica",
    tipo: "Taller",
    publicada: true,
  },
  {
    id: 6,
    slug: "festival-fin-curso",
    titulo_es: "Festival de fin de curso",
    titulo_eu: "Ikasturte amaierako jaialdia",
    descripcion_es: "Actuaciones de los alumnos en el patio del colegio. Entrada libre.",
    descripcion_eu: "Ikasleenak jokaldiak eskola-patioan. Sarrera librea.",
    fecha_inicio: "2026-06-19",
    fecha_fin: "2026-06-19",
    ubicacion: "Patio principal",
    tipo: "Festival",
    publicada: true,
  },
  {
    id: 7,
    slug: "asamblea-anual",
    titulo_es: "Asamblea anual de socios",
    titulo_eu: "Bazkideen urteko batzarra",
    descripcion_es: "Asamblea ordinaria anual. Presentacion de cuentas y eleccion de junta.",
    descripcion_eu: "Urteko ohiko batzarra. Kontu aurkezpena eta batzorde hautaketa.",
    fecha_inicio: "2026-06-10",
    fecha_fin: "2026-06-10",
    ubicacion: "Salón de actos",
    tipo: "Reunion",
    publicada: true,
  },
];

export const mockConsejos: Consejo[] = [
  {
    id: 1,
    slug: "rutina-estudio",
    titulo_es: "Rutinas de estudio en casa",
    titulo_eu: "Etxeko ikasketa errutinak",
    contenido_es: "Proximamente publicaremos recomendaciones de orientacion familiar.",
    contenido_eu: "Laster familiei zuzendutako orientazio gomendioak argitaratuko ditugu.",
    imagen_url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
    orden: 1,
    publicado: true,
  },
];

export const mockDocumentosComedor: DocumentoComedor[] = [
  {
    id: 1,
    mes: "Mayo",
    anio: 2026,
    pdf_es_url: "#",
    pdf_eu_url: "#",
    publicado: true,
  },
  {
    id: 2,
    mes: "Junio",
    anio: 2026,
    pdf_es_url: "#",
    pdf_eu_url: "#",
    publicado: true,
  },
];
